baseURL: "https://shi-ce.github.io"
title: Ce Shi, Beijing International Studies University
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

params:
    description: "My name is Ce Shi (史策, 사책), a full-time lecturer at Beijing International Studies University."
    author: Ce Shi
    googleAnalyticsID: "G-28EY7KY9DC"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ce Shi
          subtitle: "My name is Ce Shi (史策, 사책), and I’m a full-time lecturer at Beijing International Studies University. I received my Ph.D. in Literature from Korea University in August 2024. My research interests include modern Korean literature, comparative literature, digital humanities, and Chinese <i>Dongbei</i> literature. Please refer to my CV for more information."
          imageUrl: "profile.jpg"
          imageWidth: 260
          imageHeight: 260
          buttons:
            - name: Curriculum Vitae
              url: https://www.dropbox.com/scl/fi/6ird4qae5wamzohq01htq/CeShi_CV_June2026.pdf?rlkey=k6dl2kfqi4cdu45eyo80irl4a&st=5tu38171&dl=0
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ce Shi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
